name: Deploy to development environment

# Control when the action will run.
on:
  # Triggers the workflow on push events only for the main branch
  push:

  # Allows to run the workflow manually from the Actions tab
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      test-execution:
        type: boolean
        default: true
        description: 'Execute test job (Default: yes)'
# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-s3-workflow:
    name: Graasp Player
    # Reference reusable workflow file. Using the commit SHA is the safest for stability and security
    uses: graasp/graasp-deploy/.github/workflows/cintegration-s3.yml@44398dceef93d91a4125a2b3e432a3c60ba204bc
    with:
      build-folder: 'build'
      graasp-compose-host-test: 'http://localhost:3111'
      graasp-authentication-host-test: 'http://localhost:3001'
      node-env-test: 'test'
      hidden-item-tag-id-test: '12345678-1234-1234-1234-123456789012'
      public-tag-id-test: '22345678-1234-1234-1234-123456789013'
      test-execution: ${{ inputs.test-execution }}
    secrets:
      api-host: ${{ secrets.REACT_APP_API_HOST_DEV }}
      authentication-host: ${{ secrets.REACT_APP_AUTHENTICATION_HOST_DEV }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      aws-region: ${{ secrets.AWS_REGION_DEV }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      aws-s3-bucket-name: ${{ secrets.AWS_S3_BUCKET_NAME_GRAASP_PERFORM_DEV }}
      cloudfront-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_GRAASP_PERFORM_DEV }}
      domain: ${{ secrets.REACT_APP_DOMAIN_DEV }}
      graasp-compose-host: ${{ secrets.BUILDER_CLIENT_HOST_DEV }}
      graasp-explorer-host: ${{ secrets.EXPLORER_CLIENT_HOST_DEV }}
      h5p-integration-url: ${{ secrets.H5P_INTEGRATION_URL_DEV }}
      port: ${{ secrets.PORT }}
      show-notifications: ${{ secrets.REACT_APP_SHOW_NOTIFICATIONS }}
      api-host-test: ${{ secrets.REACT_APP_API_HOST }}
